source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'UnityFramework' do
  pod 'Firebase/Auth', '12.0.0'
  pod 'Firebase/Core', '12.0.0'
  pod 'Firebase/Messaging', '12.0.0'
  pod 'FirebaseFirestore', '12.0.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
